package entities.ENUMS;

public enum tileType {CORNER_TOP_LEFT,CORNER_TOP_RIGHT,CORNER_BOT_RIGHT,CORNER_BOT_LEFT,CENTER,TOP_SIDE,LEFT_SIDE,BOT_SIDE,RIGHT_SIDE
    ,MINI_TOP,MINI_V_SIDE,MINI_BOT,MINI_CENTER
    ,MINI_H_SIDE,MINI_LEFT,MINI_RIGHT};
